name: CI

on:
  push:

jobs:
  test:
    name: Test Rust SDK
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Prepare OpenAPI Generator, NodeJS, NPM, Rust
      shell: bash
      run: |
           sudo apt-get update
           sudo apt-get -y install curl nodejs npm
           npm install @openapitools/openapi-generator-cli -g
           openapi-generator-cli version-manager set 5.3.0
           npm install @openapitools/openapi-generator-cli -D
           curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
           cargo --version
    - name: Build Rust SDK
      shell: bash
      run: |
          openapi-generator-cli generate --generator-name rust --output tmf634-client --additional-properties packageName=tmf634-client -i https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF634-ResourceCatalog-v4.1.0.swagger.json
          openapi-generator-cli generate --generator-name rust-server --output tmf634-server --additional-properties packageName=tmf634-server -i https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF634-ResourceCatalog-v4.1.0.swagger.json
          openapi-generator-cli generate --generator-name rust --output tmf639-client --additional-properties packageName=tmf639-client -i https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF639-ResourceInventory-v4.0.0.swagger.json
          openapi-generator-cli generate --generator-name rust-server --output tmf639-server --additional-properties packageName=tmf639-server -i https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF639-ResourceInventory-v4.0.0.swagger.json
          sed -ie '/#\[validate(/a            length(min=1)' tmf{634,639}-server/src/models.rs
          for dir in tmf*/ ; do
              cargo build --manifest-path="$dir"Cargo.toml
              cargo doc --manifest-path="$dir"Cargo.toml
          done
